### ISSUE TITLE
Music generally to loud

### ISSUE THREAD

**Issue by klemmchr** [maca134/arma-nradio#1]
The music is really too loud in general. Using volume 1 and it's bearable but everything higher is really too loud. Maybe adjusting the whole thing to 1/3 or something like this.

PS: The addon is so fucking awesome!

**Comment by maca134** [comment]
If you look here https://github.com/maca134/arma-nradio/blob/master/src/nRadio/DllEntry.cs#L142

I may have miss understood some documentation, most of the C# got written in an evening just testing whether something like this would work.

**Comment by klemmchr** [comment]
Yeah, already saw this but I don't have any clue of C# so I can't help you with that issue.

Btw: sended you a email ;)

**Comment by maca134** [comment]
I havnt received anything...
