### ISSUE TITLE
Fetch Stream Metadata

### ISSUE THREAD

**Issue by klemmchr** [maca134/arma-nradio#3]
Option to fetch stream metadata from extension

**Comment by maca134** [comment]
I knew someone was going to ask that lol. I dont know how to do that at the moment, u got any ideas?

**Comment by maca134** [comment]
Not been able to test it with a stream yet but has been added to version 0.0.0.2

**Comment by klemmchr** [comment]
Will test it asap and give you feedback :)

**Comment by klemmchr** [comment]
Tested it a bit, works fine!
