### ISSUE TITLE
Changing volume when not playing a stream

### ISSUE THREAD

**Issue by klemmchr** [maca134/arma-nradio#4]
As I assume it's not possible to change volume when no stream is played. Would be nice to make it possible to change this when not playing to ensure that the stream volume is not too loud when starting playing.

**Comment by maca134** [comment]
This shouldnt be a problem now
https://github.com/maca134/arma-nradio/releases/tag/0.0.0.3

**Comment by klemmchr** [comment]
Big thanks ;)
